apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "mydatabase"
