apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - simple-app.local
    secretName: simple-app-tls
  - hosts:
    - simple-app2.local
    secretName: simple-app2-tls
  rules:
  - host: simple-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-service
            port:
              number: 80
  - host: simple-app2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app2-service
            port:
              number: 80
